### ISSUE TITLE
ImportError: No module named BeautifulSoup

### ISSUE THREAD

**Issue by megrimm** [alombarte/raspberry-osmc-automated#5]
i installed BeautifulSoup manually which got rid of error but on a virgin osmc/your-script install this error was given:

Running periscope-0.2.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3Lho_7/periscope-0.2.4/egg-dist-tmp-glH3Au
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('setuptools==5.5.1', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2199, in main
    lambda: setup(
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2185, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2202, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 393, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 636, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 666, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 856, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1063, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 68, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 114, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 67, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3Lho_7/periscope-0.2.4/setup.py", line 2, in <module>
  File "/tmp/easy_install-3Lho_7/periscope-0.2.4/periscope/__init__.py", line 1, in <module>
  File "/tmp/easy_install-3Lho_7/periscope-0.2.4/periscope/periscope.py", line 38, in <module>
  File "/tmp/easy_install-3Lho_7/periscope-0.2.4/periscope/plugins/**init**.py", line 20, in <module>
  File "/tmp/easy_install-3Lho_7/periscope-0.2.4/periscope/plugins/Subtitulos.py", line 20, in <module>
ImportError: No module named BeautifulSoup

**Comment by alombarte** [comment]
This is something I had pending to upload and you remind me to do it:
 https://github.com/alombarte/raspberry-osmc-automated/commit/7b85739e60b8ff3b14e439beb3ac498de036758c

I just disabled Periscope and left Subliminal for subtitles only. With subliminal you can integrate your own addic7ed account. I've been using it for a long time and works fine. I close this task since the project won't use periscope anymore.
