### ISSUE TITLE
pkg_resources.DistributionNotFound: funcsigs

### ISSUE THREAD

**Issue by bverc** [alombarte/raspberry-osmc-automated#8]
When I try and run `flexget execute` from ssh (I assume this happens from cron as well) I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: funcsigs
```

**Comment by alombarte** [comment]
I don't know where this comes from, probably another added dependency.

Try: `pip install funcsigs` and if it works we could add the dependency.

**Comment by bverc** [comment]
Thanks for the prompt response. I did as suggested. I fsrt needed to update pip as I got the errorr: `ImportError: cannot import name 'IncompleteRead'` this is explained here:
http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

Once pip was updated, I updated funcsigs as well as:

futures
tzlocal>=1.2
babelfish>=0.5.5
rebulk>=0.7.0
functools32
MarkupSafe
plumbum

Once all are installed, the next run of flexget errors:

```

2016-10-28 21:49 WARNING  manager                       Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.
2016-10-28 21:49 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/FlexGet-2.5.3-py2.7.egg/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/FlexGet-2.5.3-py2.7.egg/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/FlexGet-2.5.3-py2.7.egg/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker
  File "/usr/local/lib/python2.7/dist-packages/FlexGet-2.5.3-py2.7.egg/flexget/api/core/authentication.py", line 7, in <module>
    from flask_login import login_user, LoginManager, current_user, current_app
ImportError: cannot import name current_app
2016-10-28 21:49 VERBOSE  manager                       Creating new database /home/osmc/.flexget/db-config.sqlite - DO NOT INTERUPT ...
2016-10-28 21:49 CRITICAL manager                       [/tasks/sort-files] The key `find` is not valid here. Only known plugin names are valid keys.
2016-10-28 21:49 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
Could not start manager: Did not pass schema `validation.
```

Not really sure where to go from here.

**Comment by alombarte** [comment]
Looks like you are there.

Last error I think was raised because you haven't indented properly the configuration file. Are you using exactly 4 spaces (or 2) for each indentation level?

**Comment by bverc** [comment]
I haven't modified the config file. Spaces are all 2, 4 and 6. Any other ideas?

Appreciate your assistance.

**Comment by bverc** [comment]
Ah I see that 'find' was replaced with 'filesystem'

http://discuss.flexget.com/t/recipe-not-working-find-isnt-valid-in-sort-files/2183

Replacing 'find' with 'filesystem' in the config file seems to get the ball rolling.

**Comment by devops-faith** [comment]
Thanks bverc for finding out the root cause. I will fix it in the next commit.

**Comment by alombarte** [comment]
Thanks Brendan, I have updated the config file
